version: '3.1'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DATABASE}
    networks:
      - camagru-network

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app/src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - camagru-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - camagru-network

networks:
  camagru-network:

volumes:
  db_data:
